import Category from "models/category.model";

export const categoriesMockData: Category[] = [
  {
    id: 1,
    parent_id: null,
    name: "Technology",
    display_name: "Technology",
    describe: "Technology",
    slug: "technology",
    thumbnail: "",
    status: "active",
    created_timestamp: "2020-01-01 00:00:00",
    last_modified_timestamp: "2020-01-01 00:00:00",
  },
  {
    id: 2,
    parent_id: null,
    name: "Development",
    display_name: "Development",
    describe: "Development",
    slug: "development",
    thumbnail: "",
    status: "active",
    created_timestamp: "2020-01-01 00:00:00",
    last_modified_timestamp: "2020-01-01 00:00:00",
  },
  {
    id: 3,
    parent_id: null,
    name: "Blogs",
    display_name: "Blogs",
    describe: "Blogs",
    slug: "blogs",
    thumbnail: "",
    status: "active",
    created_timestamp: "2020-01-01 00:00:00",
    last_modified_timestamp: "2020-01-01 00:00:00",
  },
  {
    id: 4,
    parent_id: null,
    name: "Discussions",
    display_name: "Discussions",
    describe: "Discussions",
    slug: "discussions",
    thumbnail: "",
    status: "active",
    created_timestamp: "2020-01-01 00:00:00",
    last_modified_timestamp: "2020-01-01 00:00:00",
  },
  {
    id: 5,
    parent_id: null,
    name: "Community",
    display_name: "Community",
    describe: "Community",
    slug: "community",
    thumbnail: "",
    status: "active",
    created_timestamp: "2020-01-01 00:00:00",
    last_modified_timestamp: "2020-01-01 00:00:00",
  },
  {
    id: 6,
    parent_id: null,
    name: "News",
    display_name: "News",
    describe: "News",
    slug: "news",
    thumbnail: "",
    status: "active",
    created_timestamp: "2020-01-01 00:00:00",
    last_modified_timestamp: "2020-01-01 00:00:00",
  },
  {
    id: 7,
    parent_id: null,
    name: "Marketing",
    display_name: "Marketing",
    describe: "Marketing",
    slug: "marketing",
    thumbnail: "",
    status: "active",
    created_timestamp: "2020-01-01 00:00:00",
    last_modified_timestamp: "2020-01-01 00:00:00",
  },
  {
    id: 8,
    parent_id: 6,
    name: "Design",
    display_name: "Design",
    describe: "Design",
    slug: "design",
    thumbnail: "",
    status: "active",
    created_timestamp: "2020-01-01 00:00:00",
    last_modified_timestamp: "2020-01-01 00:00:00",
  }
]