import Comment from "models/comment.model";
import { minusDay } from 'utils/commonFunction';
import dayjs from 'dayjs';

export const commentsMockData: Comment[] = [
  {
    id: 1000,
    parent_id: null,
    owner: {
      id: '111',
      first_name: 'Vinh',
      last_name: 'Trinh',
      display_name: 'Ngọc Vĩnh',
      user_name: 'vinhtrinh',
      avatar: '',
    },
    post_id: '1',
    content: 'English translation for this series is available at ./translations/EN folder',
    status: 'Active',
    likes: 132,
    dislikes: 1455,
    replies: 2,
    created_timestamp: dayjs(minusDay(5)).format('YYYY-MM-DD HH:mm:SSS'),
    children: [],
  },
  {
    id: 1001,
    parent_id: null,
    owner: {
      id: '111',
      first_name: 'Vinh',
      last_name: 'Trinh',

      display_name: 'Ngọc Vĩnh',
      user_name: 'vinhtrinh',
      avatar: 'https://placeimg.com/320/320',
    },
    post_id: '1',
    content: 'English translation for this series: https://www.facebook.com/tnvinh00/. Angular Helmet is a simple and intuitive document head manager for Angular applications. Inspired by React Helmet.',
    status: 'Active',
    likes: 2012,
    dislikes: 15,
    replies: 2,
    created_timestamp: dayjs(minusDay(20)).format('YYYY-MM-DD HH:mm:SSS'),
    children: [],
  },
  {
    id: 1002,
    parent_id: '1000',
    owner: {
      id: '111',
      first_name: 'Vinh',
      last_name: 'Trinh',

      display_name: 'Ngọc Vĩnh',
      user_name: 'vinhtrinh',
      avatar: 'https://placeimg.com/320/320',
    },
    post_id: '1',
    content: 'English translation for this series is available at ./translations/EN folder',
    status: 'Active',
    likes: 20,
    dislikes: 0,
    replies: 2,
    created_timestamp: dayjs(minusDay(10)).format('YYYY-MM-DD HH:mm:SSS'),
    last_modified_timestamp: dayjs(minusDay(10)).format('YYYY-MM-DD HH:mm:SSS'),
    children: [],
  },
  {
    id: 1003,
    parent_id: '1002',
    owner: {
      id: '111',
      first_name: 'Vinh',
      last_name: 'Trinh',

      display_name: 'Ngọc Vĩnh',
      user_name: 'vinhtrinh',
      avatar: 'https://placeimg.com/320/320',
    },
    post_id: '1',
    content: 'English translation for this series is available at ./translations/EN folder',
    status: 'Active',
    likes: 1,
    dislikes: 0,
    replies: 2,
    created_timestamp: dayjs(minusDay(12)).format('YYYY-MM-DD HH:mm:SSS'),
    last_modified_timestamp: dayjs(minusDay(12)).format('YYYY-MM-DD HH:mm:SSS'),
    children: [],
  },
  {
    id: 1004,
    parent_id: null,
    owner: {
      id: '111',
      first_name: 'Vinh',
      last_name: 'Trinh',

      display_name: 'Ngọc Vĩnh',
      user_name: 'vinhtrinh',
      avatar: '',
    },
    post_id: '1',
    content: 'English translation for this series: https://www.facebook.com/tnvinh00/. Angular Helmet is a simple and intuitive document head manager for Angular applications. Inspired by React Helmet.',
    status: 'Active',
    likes: 2121212,
    dislikes: 150212,
    replies: 2,
    created_timestamp: dayjs(minusDay(2)).format('YYYY-MM-DD HH:mm:SSS'),
    last_modified_timestamp: dayjs(minusDay(2)).format('YYYY-MM-DD HH:mm:SSS'),
    children: [],
  },
  {
    id: 1005,
    parent_id: '1002',
    owner: {
      id: '111',
      first_name: 'Vinh',
      last_name: 'Trinh',

      display_name: 'Ngọc Vĩnh',
      user_name: 'vinhtrinh',
      avatar: 'https://placeimg.com/320/320',
    },
    post_id: '1',
    content: 'English translation for this series is available at ./translations/EN folder',
    status: 'Active',
    likes: 2012,
    dislikes: 15,
    replies: 2,
    created_timestamp: dayjs(minusDay(3)).format('YYYY-MM-DD HH:mm:SSS'),
    last_modified_timestamp: dayjs(minusDay(3)).format('YYYY-MM-DD HH:mm:SSS'),
    children: [],
  },
  {
    id: 1006,
    parent_id: '1000',
    owner: {
      id: '111',
      first_name: 'Vinh',
      last_name: 'Trinh',

      display_name: 'Ngọc Vĩnh',
      user_name: 'vinhtrinh',
      avatar: '',
    },
    post_id: '1',
    content: 'English translation for this series is available at ./translations/EN folder',
    status: 'Active',
    likes: 2,
    dislikes: 150,
    replies: 2,
    created_timestamp: dayjs(minusDay(8)).format('YYYY-MM-DD HH:mm:SSS'),
    last_modified_timestamp: dayjs(minusDay(8)).format('YYYY-MM-DD HH:mm:SSS'),
    children: [],
  },
  {
    id: 1007,
    parent_id: null,
    owner: {
      id: '111',
      first_name: 'Vinh',
      last_name: 'Trinh',

      display_name: 'Ngọc Vĩnh',
      user_name: 'vinhtrinh',
      avatar: 'https://placeimg.com/320/320',
    },
    post_id: '1',
    content: 'English translation for this series is available at ./translations/EN folder',
    status: 'Active',
    likes: 0,
    dislikes: 1,
    replies: 2,
    created_timestamp: dayjs(minusDay(30)).format('YYYY-MM-DD HH:mm:SSS'),
    last_modified_timestamp: dayjs(minusDay(30)).format('YYYY-MM-DD HH:mm:SSS'),
    children: [],
  },
  {
    id: 1008,
    parent_id: '1007',
    owner: {
      id: '111',
      first_name: 'Vinh',
      last_name: 'Trinh',

      display_name: 'Ngọc Vĩnh',
      user_name: 'vinhtrinh',
      avatar: '',
    },
    post_id: '1',
    content: 'English translation for this series is available at ./translations/EN folder',
    status: 'Active',
    likes: 0,
    dislikes: 1,
    replies: 2,
    created_timestamp: dayjs(minusDay(8)).format('YYYY-MM-DD HH:mm:SSS'),
    last_modified_timestamp: dayjs(minusDay(8)).format('YYYY-MM-DD HH:mm:SSS'),
    children: [],
  },
  {
    id: 1009,
    parent_id: '1007',
    owner: {
      id: '111',
      first_name: 'Vinh',
      last_name: 'Trinh',

      display_name: 'Ngọc Vĩnh',
      user_name: 'vinhtrinh',
      avatar: 'https://placeimg.com/320/320',
    },
    post_id: '1',
    content: 'English translation for this series is available at ./translations/EN folder',
    status: 'Active',
    likes: 0,
    dislikes: 1,
    replies: 2,
    created_timestamp: dayjs(minusDay(5)).format('YYYY-MM-DD HH:mm:SSS'),
    last_modified_timestamp: dayjs(minusDay(5)).format('YYYY-MM-DD HH:mm:SSS'),
    children: [],
  },
  {
    id: 1010,
    parent_id: null,
    owner: {
      id: '111',
      first_name: 'Vinh',
      last_name: 'Trinh',

      display_name: 'Ngọc Vĩnh',
      user_name: 'vinhtrinh',
      avatar: 'https://placeimg.com/320/320',
    },
    post_id: '1',
    content: 'English translation for this series is available at ./translations/EN folder',
    status: 'Active',
    likes: 0,
    dislikes: 1,
    replies: 2,
    created_timestamp: dayjs(minusDay(15)).format('YYYY-MM-DD HH:mm:SSS'),
    last_modified_timestamp: dayjs(minusDay(20)).format('YYYY-MM-DD HH:mm:SSS'),
    children: [],
  }
]