import Tag from "models/tag.model";

export const tagsMockData: Tag[] = [
  {
    id: '1',
    tag: 'angular',
    name: 'Angular',
    describe: 'Angular is a TypeScript-based open-source web application platform led by the Angular Team at Google and by a community of individuals and corporations. Angular is a complete rewrite from the same team that built AngularJS.',
    status: 'active',
    created_timestamp: '2020-01-01 00:00:00',
    last_modified_timestamp: '2020-01-01 00:00:00',
  },
  {
    id: '2',
    tag: 'react',
    name: 'React',
    describe: 'React is a JavaScript library for building user interfaces. It is maintained by Facebook and a community of individual developers and companies. React can be used as a base in the development of single-page or mobile applications.',
    status: 'active',
    created_timestamp: '2020-01-01 00:00:00',
    last_modified_timestamp: '2020-01-01 00:00:00',
  },
  {
    id: '3',
    tag: 'vue',
    name: 'Vue',
    describe: 'Vue.js is an open-source JavaScript framework for building user interfaces. It is maintained by a community of individual developers and companies. Vue can be used as a base in the development of single-page or mobile applications.',
    status: 'active',
    created_timestamp: '2020-01-01 00:00:00',
    last_modified_timestamp: '2020-01-01 00:00:00',
  },
  {
    id: '4',
    tag: 'angular-cli',
    name: 'Angular CLI',
    describe: 'Angular CLI is a command-line interface for the Angular development platform. It is used to create and manage projects for the Angular framework.',
    status: 'active',
    created_timestamp: '2020-01-01 00:00:00',
    last_modified_timestamp: '2020-01-01 00:00:00',
  },
  {
    id: '',
    tag: 'react-native',
    name: 'React Native',
    describe: 'React Native is a framework for building native apps using React. It is maintained by Facebook and a community of individual developers and companies.',
    status: 'active',
    created_timestamp: '2020-01-01 00:00:00',
    last_modified_timestamp: '2020-01-01 00:00:00',
  },
  {
    id: '',
    tag: 'vue-cli',
    name: 'Vue CLI',
    describe: 'Vue CLI is a command-line interface for the Vue.js development platform. It is used to create and manage projects for the Vue framework.',
    status: 'active',
    created_timestamp: '2020-01-01 00:00:00',
    last_modified_timestamp: '2020-01-01 00:00:00',
  },
  {
    id: '',
    tag: 'webpack',
    name: 'Webpack',
    describe: 'Webpack is a module bundler that packs multiple modules with dependencies into a single module. It is maintained by a community of individual developers and companies.',
    status: 'active',
    created_timestamp: '2020-01-01 00:00:00',
    last_modified_timestamp: '2020-01-01 00:00:00',
  },
  {
    id: '',
    tag: 'gulp',
    name: 'Gulp',
    describe: 'Gulp is a streaming build system. It is maintained by a community of individual developers and companies.',
    status: 'active',
    created_timestamp: '2020-01-01 00:00:00',
    last_modified_timestamp: '2020-01-01 00:00:00',
  },
  {
    id: '',
    tag: 'sass',
    name: 'Sass',
    describe: 'Sass is a stylesheet language that is interpreted into Cascading Style Sheets (CSS). It is maintained by a community of individual developers and companies.',
    status: 'active',
    created_timestamp: '2020-01-01 00:00:00',
    last_modified_timestamp: '2020-01-01 00:00:00',
  },
  {
    id: '',
    tag: 'less',
    name: 'Less',
    describe: 'Less is a stylesheet language that is interpreted into Cascading Style Sheets (CSS). It is maintained by a community of individual developers and companies.',
    status: 'active',
    created_timestamp: '2020-01-01 00:00:00',
    last_modified_timestamp: '2020-01-01 00:00:00',
  },
  {
    id: '',
    tag: 'bootstrap',
    name: 'Bootstrap',
    describe: 'Bootstrap is a free and open-source front-end web framework for designing websites and web applications. It is maintained by a community of individual developers and companies.',
    status: 'active',
    created_timestamp: '2020-01-01 00:00:00',
    last_modified_timestamp: '2020-01-01 00:00:00',
  },
  {
    id: '',
    tag: 'material-ui',
    name: 'Material-UI',
    describe: 'Material-UI is a React component library that enables you to create beautiful, high-fidelity, mobile-first experiences. It is maintained by a community of individual developers and companies.',
    status: 'active',
    created_timestamp: '2020-01-01 00:00:00',
    last_modified_timestamp: '2020-01-01 00:00:00',
  },
  {
    id: '',
    tag: 'material-design',
    name: 'Material Design',
    describe: 'Material Design is a design language developed by Google. It is used to create a consistent and beautiful user experience across all products on Android, iOS, and the web.',
    status: 'active',
    created_timestamp: '2020-01-01 00:00:00',
    last_modified_timestamp: '2020-01-01 00:00:00',
  },
  {
    id: '',
    tag: 'material-icons',
    name: 'Material Icons',
    describe: 'Material Icons is a set of open source icons for use in web and mobile applications. It is maintained by a community of individual developers and companies.',
    status: 'active',
    created_timestamp: '2020-01-01 00:00:00',
    last_modified_timestamp: '2020-01-01 00:00:00',
  },
  {
    id: '',
    tag: 'bootstrap-vue',
    name: 'Bootstrap Vue',
    describe: 'Bootstrap Vue is a Vue.js wrapper for Bootstrap. It is maintained by a community of individual developers and companies.',
    status: 'active',
    created_timestamp: '2020-01-01 00:00:00',
    last_modified_timestamp: '2020-01-01 00:00:00',
  },
  {
    id: '',
    tag: 'vue-router',
    name: 'Vue Router',
    describe: 'Vue Router is a routing library for Vue.js. It is maintained by a community of individual developers and companies.',
    status: 'active',
    created_timestamp: '2020-01-01 00:00:00',
    last_modified_timestamp: '2020-01-01 00:00:00',
  },
  {
    id: '',
    tag: 'vuex',
    name: 'Vuex',
    describe: 'Vuex is a state management pattern and library for Vue.js applications. It is maintained by a community of individual developers and companies.',
    status: 'active',
    created_timestamp: '2020-01-01 00:00:00',
    last_modified_timestamp: '2020-01-01 00:00:00',
  },
  {
    id: '',
    tag: 'vue-i18n',
    name: 'Vue I18n',
    describe: 'Vue I18n is a localization library for Vue.js. It is maintained by a community of individual developers and companies.',
    status: 'active',
    created_timestamp: '2020-01-01 00:00:00',
    last_modified_timestamp: '2020-01-01 00:00:00',
  },
  {
    id: '',
    tag: 'vue-resource',
    name: 'Vue Resource',
    describe: 'Vue Resource is a REST client for Vue.js. It is maintained by a community of individual developers and companies.',
    status: 'active',
    created_timestamp: '2020-01-01 00:00:00',
    last_modified_timestamp: '2020-01-01 00:00:00',
  },
  {
    id: '',
    tag: 'vue-router-i18n',
    name: 'Vue Router I18n',
    describe: 'Vue Router I18n is a localization library for Vue Router. It is maintained by a community of individual developers and companies.',
    status: 'active',
    created_timestamp: '2020-01-01 00:00:00',
    last_modified_timestamp: '2020-01-01 00:00:00',
  },
  {
    id: '',
    tag: 'dotnet',
    name: '.NET',
    describe: '.NET is a programming language and runtime environment developed by Microsoft. It is maintained by a community of individual developers and companies.',
    status: 'active',
    created_timestamp: '2020-01-01 00:00:00',
    last_modified_timestamp: '2020-01-01 00:00:00',
  },
  {
    id: '',
    tag: 'csharp',
    name: 'CSharp',
    describe: 'C# is a programming language and runtime environment developed by Microsoft. It is maintained by a community of individual developers and companies.',
    status: 'active',
    created_timestamp: '2020-01-01 00:00:00',
    last_modified_timestamp: '2020-01-01 00:00:00',
  },
  {
    id: '',
    tag: 'aspnet',
    name: 'ASP.NET',
    describe: 'ASP.NET is a web application framework developed by Microsoft. It is maintained by a community of individual developers and companies.',
    status: 'active',
    created_timestamp: '2020-01-01 00:00:00',
    last_modified_timestamp: '2020-01-01 00:00:00',
  },
  {
    id: '',
    tag: 'aspnet-core',
    name: 'ASP.NET Core',
    describe: 'ASP.NET Core is a web application framework developed by Microsoft. It is maintained by a community of individual developers and companies.',
    status: 'active',
    created_timestamp: '2020-01-01 00:00:00',
    last_modified_timestamp: '2020-01-01 00:00:00',
  },
  {
    id: '',
    tag: 'nextjs',
    name: 'Next.js',
    describe: 'Next.js is a JavaScript framework for building web applications. It is maintained by a community of individual developers and companies.',
    status: 'active',
    created_timestamp: '2020-01-01 00:00:00',
    last_modified_timestamp: '2020-01-01 00:00:00',
  },
  {
    id: '',
    tag: 'react-router',
    name: 'React Router',
    describe: 'React Router is a routing library for React. It is maintained by a community of individual developers and companies.',
    status: 'active',
    created_timestamp: '2020-01-01 00:00:00',
    last_modified_timestamp: '2020-01-01 00:00:00',
  },
  {
    id: '',
    tag: 'react-router-dom',
    name: 'React Router DOM',
    describe: 'React Router DOM is a routing library for React. It is maintained by a community of individual developers and companies.',
    status: 'active',
    created_timestamp: '2020-01-01 00:00:00',
    last_modified_timestamp: '2020-01-01 00:00:00',
  },
  {
    id: '',
    tag: 'react-redux',
    name: 'React Redux',
    describe: 'React Redux is a state management library for React. It is maintained by a community of individual developers and companies.',
    status: 'active',
    created_timestamp: '2020-01-01 00:00:00',
    last_modified_timestamp: '2020-01-01 00:00:00',
  },
  {
    id: '',
    tag: 'react-router-redux',
    name: 'React Router Redux',
    describe: 'React Router Redux is a routing library for React. It is maintained by a community of individual developers and companies.',
    status: 'active',
    created_timestamp: '2020-01-01 00:00:00',
    last_modified_timestamp: '2020-01-01 00:00:00',
  },
  {
    id: '2',
    tag: 'react-native',
    name: 'React Native',
    describe: 'React Native is a JavaScript framework for building native apps. It is maintained by a community of individual developers and companies.',
    status: 'active',
    created_timestamp: '2020-01-01 00:00:00',
    last_modified_timestamp: '2020-01-01 00:00:00',
  }
];